//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anagrams.EF.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public long ID { get; set; }
        public string IP_address { get; set; }
        public int CachedWordID { get; set; }
        public System.DateTime SearchTime { get; set; }
    
        public virtual CachedWord CachedWord { get; set; }
    }
}
